### ISSUE TITLE
LineSeries Refresh Bugs

### ISSUE THREAD

**Issue by supergh** [Live-Charts/LiveCharts2#2050]
**Bug Description**
In my project, I use LineSeries to display the values, but when the new values are specified, there are still things I drew before.

**Screenshot**
Please refer to the attached screen.

**Desktop (please complete the following information):**:
- OS: Windows 10 22H2

** Refresh values in my code
<img width="613" height="152" alt="Image" src="https://github.com/user-attachments/assets/8d2fa7c4-303d-4e23-bf48-c0223818c11f" />

** 12.01 A screen with a normal date line
<img width="1108" height="392" alt="Image" src="https://github.com/user-attachments/assets/5dd9e3ad-8dcf-4523-96e5-a8d6e0c65422" />

** 11.30 A screen with a normal date line
<img width="1130" height="426" alt="Image" src="https://github.com/user-attachments/assets/18474994-637a-4aee-8006-e26f28547c1f" />

** The screen where the line is displayed abnormally when it is returned to the 12.01 date
<img width="1130" height="429" alt="Image" src="https://github.com/user-attachments/assets/0af0239b-4ba1-402f-93f6-76144f42ed2d" />

**Comment by ping9719** [comment]
#2065 
It's similar to my problem.

**Comment by kF13Ld** [comment]
I have the same problem with WPF and Avalonia. Last working Nuget-version was 2.0.0-rc5.4.

**Comment by beto-rodriguez** [comment]
@kF13Ld this should be fixed in 2.0.2, did you try that version?

**Comment by kF13Ld** [comment]
Yes, I did. 

This is what my plots look like with 2.0.0-rc5.4:

<img width="670" height="570" alt="Image" src="https://github.com/user-attachments/assets/b81e80e6-8892-4810-8b38-aa8c79eb6442" />

And when I switch to another one, everything is fine:

<img width="680" height="581" alt="Image" src="https://github.com/user-attachments/assets/5e70e6b3-f6a4-4326-9c26-b3f276d1f06f" />



But with 2.0.2 it looks like this:
First graph (also note the bad resolution: where is that coming from?):

<img width="685" height="576" alt="Image" src="https://github.com/user-attachments/assets/d5aa44be-f6e2-43d3-86df-ce91459116d8" />

and when I switch to another graph, it shows both diagrams at the same time:

<img width="689" height="575" alt="Image" src="https://github.com/user-attachments/assets/4f088b25-2568-405e-b21f-6f16d2ca5a34" />

**Comment by beto-rodriguez** [comment]
Hi @supergh — the "old values still drawn after refresh" behavior in your screenshots was a real bug (tracked as #1970) and is fixed in 2.0.0; the regression test landed in #2220. Closing this one as fixed.

If you can still reproduce it on 2.0.2 with a minimal sample project we can `dotnet run`, please reopen and attach it and we'll take another look.

**Comment by beto-rodriguez** [comment]
Hi @kF13Ld — thanks for the screenshots, but your symptoms are actually different from the original report here (you're describing two charts overlaying after switching views + a resolution drop on first paint), so this is most likely a separate bug rather than a regression of #2050.

Two existing issues look like strong candidates for what you're hitting:
- "both diagrams visible at the same time when I switch" → #1986 (open PR #2158).
- "bad resolution on the first graph", if this is WPF inside a `TabControl` → #2029 (open PR #2233 — DPI scale being applied twice when the view is re-loaded).

Could you confirm:
1. Are the charts hosted inside a `TabControl`, `ScrollViewer`, or `Frame`/page navigation? If yes, subscribe to #1986 / #2029 — your case may already be covered there.
2. If neither matches, please open a **new** issue with: platform (WPF or Avalonia — they're separate code paths), .NET version, and ideally a minimal repro project. Screenshots alone aren't enough on this one because the same visual ("two charts on top of each other") can come from view recycling, DPI handling, or paint-task ordering, and the fix is different for each.

Thanks!

**Comment by kF13Ld** [comment]
Thanks @beto-rodriguez . I still have that problem but am unable to create a working minimal sample project. Maybe it has something to do with me mixing Avalonia and WPF windows at the same time. The main application window is Avalonia while the faulty diagrams are in a WPF subwindow.
